# nixpacks.toml

[phases.setup]
nixPkgs = [
    "nginx",
    "php",
    "php82Packages.composer",
    "nodejs-18_x",
    "supervisor"
]

[phases.install]
cmds = [
    "npm install -g pnpm@9.0.6",
    "composer install --no-dev --optimize-autoloader",
    "pnpm install",
    "cp .env.example .env",
    "php artisan key:generate --force",
    "php artisan migrate --seed --force",
    "chmod -R 755 storage/* bootstrap/cache/"
]

[phases.build]
cmds = [
    "pnpm build"
]

[start]
cmd = "supervisord -c /app/supervisord.conf"

[variables]
NIXPACKS_PHP_VERSION = "8.2"
NIXPACKS_NODE_VERSION = "18"
